synthetic-package: false

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_intl.dart
untranslated-messages-file: desiredFileName.txt
preferred-supported-locales: [en, es, es_AR, pt, pt_BR]
# To generate file with translations, run: `flutter gen-l10n`
